# Generated by Django 3.2.3 on 2021-07-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_post_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='preview',
        ),
    ]
