# Generated by Django 3.2.3 on 2021-06-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='author',
        ),
    ]
