# Generated by Django 3.2.3 on 2021-06-14 21:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staff_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
