# Generated by Django 3.2.3 on 2021-06-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='description',
            new_name='content',
        ),
    ]
