# Generated by Django 3.2.3 on 2021-06-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20210614_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='description',
            new_name='content',
        ),
    ]
