# Generated by Django 3.2.3 on 2021-07-15 16:58

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=100)),
                ('story_preview', models.CharField(max_length=200)),
                ('story_author', models.CharField(blank=True, max_length=100)),
                ('story_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('story_image', models.ImageField(blank=True, upload_to='images')),
                ('story_image_alt', models.CharField(blank=True, max_length=100)),
                ('story_date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
