# Generated by Django 3.2.3 on 2021-07-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_date_posted',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_image_alt',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_preview',
            new_name='preview',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='story_title',
            new_name='title',
        ),
    ]
