# Generated by Django 3.2.3 on 2021-07-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20210715_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='preview',
        ),
    ]
