# Generated by Django 3.2.3 on 2021-06-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_post_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Program',
        ),
    ]
