# Generated by Django 3.2.3 on 2021-06-03 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_rename_post_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
