# Generated by Django 3.2.3 on 2021-06-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_program_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='date_posted',
        ),
    ]
