# Generated by Django 3.2.3 on 2021-06-16 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
