# Generated by Django 3.2.3 on 2021-06-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_alter_program_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
