# Generated by Django 3.2.3 on 2021-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20210709_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='subtitle',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
