# Generated by Django 3.2.3 on 2021-07-13 18:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_alter_program_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('parent_email', models.EmailField(max_length=254)),
                ('student', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', phone_field.models.PhoneField(blank=True, help_text='Student phone number', max_length=31)),
                ('student_grade', models.CharField(max_length=20)),
                ('student_address', models.CharField(max_length=254)),
            ],
        ),
    ]
