# Generated by Django 3.2.3 on 2021-07-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20210713_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
