# Generated by Django 3.2.3 on 2021-07-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_program_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='student_id',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
