# Generated by Django 3.2.3 on 2021-07-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_alter_customer_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='student_id',
        ),
    ]
