# Generated by Django 3.2.3 on 2021-07-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_customer_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='student_id',
            field=models.CharField(max_length=254),
        ),
    ]
