# Generated by Django 3.2.3 on 2021-08-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_auto_20210725_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peprogram',
            name='food_program',
            field=models.BooleanField(help_text='**Only check this box if you are enrolled in the free lunch program. We will need to verify enrollement or full price will be charged at the end of the semester.', verbose_name='Payment Assistance'),
        ),
    ]
