# Generated by Django 3.2.3 on 2021-08-18 04:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_alter_peprogram_food_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotdogger',
            old_name='student_id',
            new_name='school',
        ),
        migrations.AddField(
            model_name='hotdogger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
