# Generated by Django 3.2.3 on 2021-08-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0024_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdogger',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='peprogram',
            name='coupon',
        ),
    ]
