# Generated by Django 3.2.3 on 2021-10-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0026_auto_20211004_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotdogger',
            old_name='student',
            new_name='skater',
        ),
        migrations.RenameField(
            model_name='hotdogger',
            old_name='student_email',
            new_name='skater_email',
        ),
        migrations.RenameField(
            model_name='hotdogger',
            old_name='student_grade',
            new_name='skater_grade',
        ),
        migrations.RenameField(
            model_name='hotdogger',
            old_name='student_phone',
            new_name='skater_phone',
        ),
        migrations.RenameField(
            model_name='peprogram',
            old_name='student',
            new_name='skater',
        ),
        migrations.RenameField(
            model_name='peprogram',
            old_name='student_email',
            new_name='skater_email',
        ),
        migrations.RenameField(
            model_name='peprogram',
            old_name='student_grade',
            new_name='skater_grade',
        ),
        migrations.RenameField(
            model_name='peprogram',
            old_name='student_id',
            new_name='skater_id',
        ),
        migrations.RenameField(
            model_name='peprogram',
            old_name='student_phone',
            new_name='skater_phone',
        ),
    ]
