# Generated by Django 3.2.3 on 2022-01-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0029_auto_20220107_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='peprogram',
            name='slc_number',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
