# Generated by Django 3.2.3 on 2022-01-08 01:41

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0031_rename_skater_id_peprogram_skater_school_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotdogger',
            name='parent_address',
        ),
        migrations.RemoveField(
            model_name='hotdogger',
            name='school',
        ),
        migrations.RemoveField(
            model_name='hotdogger',
            name='skater_email',
        ),
        migrations.RemoveField(
            model_name='hotdogger',
            name='skater_grade',
        ),
        migrations.RemoveField(
            model_name='hotdogger',
            name='skater_phone',
        ),
        migrations.AddField(
            model_name='hotdogger',
            name='emergency_contact',
            field=models.CharField(default='NA', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotdogger',
            name='emergency_contact_phone',
            field=phone_field.models.PhoneField(default='NA', max_length=31),
            preserve_default=False,
        ),
    ]
