# Generated by Django 3.2.3 on 2022-01-08 02:02

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0032_auto_20220107_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdogger',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
