# Generated by Django 3.2.3 on 2022-01-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0033_alter_hotdogger_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdogger',
            name='month_or_event',
            field=models.CharField(default='NA', max_length=254),
            preserve_default=False,
        ),
    ]
