# Generated by Django 3.2.3 on 2022-01-08 03:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0034_hotdogger_month_or_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdogger',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='hotdogger',
            name='emergency_contact_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
