# Generated by Django 3.2.3 on 2022-10-17 17:48

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0035_auto_20220107_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='VanTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('parent_email', models.EmailField(max_length=254)),
                ('skater', models.CharField(max_length=100)),
                ('month_or_event', models.CharField(max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=254)),
                ('emergency_contact_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
