# Generated by Django 3.2.3 on 2022-10-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0036_vantour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vantour',
            name='parent',
            field=models.CharField(max_length=105),
        ),
    ]
