# Generated by Django 3.2.3 on 2022-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0037_alter_vantour_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vantour',
            name='parent',
            field=models.CharField(max_length=100),
        ),
    ]
